### ISSUE TITLE
handling coordinated omission properly

### ISSUE THREAD

**Issue by yassinm** [openmessaging/benchmark#152]
I could not tell how the client side was immune to coordinated omission. I wonder if this is an issue or if not how do you guaranty or work around the problem ?

from [here](http://highscalability.com/blog/2015/10/5/your-load-generator-is-probably-lying-to-you-take-the-red-pi.html)

> Load testing. Load generators generate requests at a specified rate. Response times are logged for each request, put in a bucket, and percentiles are generated.

> This approach works only if all responses fit within the collection bucket interval. Let’s say requests are supposed to be sent every second, but a response takes a second and half. The generator will wait to send the next request. 

> So something problematic is missed and is not being measured. There's a kind of hidden coordination to avoid looking at a problem.

**Comment by cdbartholomew** [comment]
From what I have seen with the Kafka and Pulsar drivers, the load generator is doing asynchronous sends. So, the sending of the message should never be blocked. The one exception would be if the queue of outstanding unacknowledged send messages fills up. In that case, the send will block waiting for the queue to drain. Pulsar client can be configured to throw an exception in this case (and fail the test), but I am not aware of a configuration option in Kafka to throw an exception.

One generic solution and one I have used before is to have the load balancer generate messages at regular intervals into an internal queue. The sending client reads from this queue (in a tight loop), sending each message as they arrive. This ensures the load generator is independent of the sending client. The timestamp is created when the message is put in the internal queue, not when it is handled by the sending client. The time spent in this internal queue adds a small amount of latency but it avoids what is called the co-ordinated omission problem.

**Comment by yassinm** [comment]
I used [JLBH ASL2](https://github.com/OpenHFT/Chronicle-Core) before successfully. This helped me avoid some of the pitfalls associated with benchmarks. But specifically around the co-ordinated omission part plus other java specific issues like GC, jitter as mentioned [here](http://www.rationaljava.com/2016/04/jlbh-introducing-java-latency.html). I have not seen anything more recent that addressed these concerns properly so far. 

I also liked the fact that with chronicle i could pin my thread to a core (in linux at least) to avoid more noise in the load generator.

**Comment by merlimat** [comment]
> I could not tell how the client side was immune to coordinated omission.

The system is indeed not immune

> From what I have seen with the Kafka and Pulsar drivers, the load generator is doing asynchronous sends.

In both cases, async sends can block as well. Eg. Pulsar client is configured to block when buffer is full, the reason being to easily adjust to the max sustainable system throughput. 

> I also liked the fact that with chronicle i could pin my thread to a core (in linux at least) to avoid more noise in the load generator.

Yes, that works because the latency of an inter-thread in memory queue is orders of magnitude lower, though that noise would not be measurable here.

We can also pin thread in BK and Pulsar for low latency scenarios (at the expense of CPUs)

**Comment by yassinm** [comment]
> One generic solution and one I have used before is to have the load balancer generate messages at regular intervals into an internal queue

You can get all sorts of interference like GC stalls in the load generator which i think will invalidate the above assumption. I don't think you can guaranty the queue producer/consumer to be free from these side effects.

Which is why i always preferred if someone else already took care of these distractions :-) I don't think i would attempt to write a micro benchmark without JMH nowadays. I assume the same is true with macro (for the lack of a better word) benchmarks. There are so many things you have to be careful about :-(

**Comment by cdbartholomew** [comment]
> You can get all sorts of interference like GC stalls in the load generator which i think will invalidate the above assumption. I don't think you can guaranty the queue producer/consumer to be free from these side effects.

For the project I was referring to, the load generator was written in C, so no GC stalls. I have also worked on projects where we used a Java Native Interface (JNI) wrapper for the C code to get low, consistent latency in Java.
