### ISSUE TITLE
Pulsar old version of distribution has been deleted from Apache site

### ISSUE THREAD

**Issue by Tristan1900** [openmessaging/benchmark#165]
This line seems not working anymore https://github.com/openmessaging/openmessaging-benchmark/blob/master/driver-pulsar/deploy/deploy.yaml#L68.

I navigate to http://apache.osuosl.org/pulsar/ and only found the latest version `2.5.0` whereas Bookkeeper and Zookeeper keep their previous released versions. Is it on purpose to delete the old Pulsar versions? 

Thanks

**Comment by dave2wave** [comment]
Older releases are always found at archive.apache.org

**Comment by dave2wave** [comment]
Here is policy regarding current versions of ASF project releases vs. archive:

https://infra.apache.org/release-distribution.html#archival
