### ISSUE TITLE
Pulsar driver unable to use listener name feature in pulsar 2.6.0

### ISSUE THREAD

**Issue by meleagle** [openmessaging/benchmark#177]
Pulsar 2.6.0 released a new feature where you can advertise multiple addresses.  This also comes with the requirement that the consumer must specify the listener name that it wants to use for communication between it and the broker, like below:

```java
PulsarClient.builder()
    .serviceUrl(url)
    .listenerName("internal")
    .build();
```

Currently since the listener name cannot be set the multiple addresses feature is unusable and the consumer cannot connect to a pulsar cluster that requires multiple advertised addresses.

Pulsar 2.6.0 release docs:
https://pulsar.apache.org/blog/2020/06/18/Apache-Pulsar-2-6-0/

**Comment by vongosling** [comment]
Stale issue will be close.
