### ISSUE TITLE
AnsibleUndefinedVariable: 'ansible.vars.hostvars.HostVarsVars object' has no attribute

### ISSUE THREAD

**Issue by rahulpandeycs** [openmessaging/benchmark#188]
I've been following the Readme file to setup kafka-driver tests on my ec2. While running the ansible-playbook as described in http://openmessaging.cloud/docs/benchmarks/kafka/ the Zookeeper setup is failing with error:

TASK [template] ********************************************************************************************************
fatal: [52.24.***.*]: FAILED! => {"changed": false, "msg": "AnsibleUndefinedVariable: 'ansible.vars.hostvars.HostVarsVars object' has no attribute 'private_ip'"}
fatal: [54.***.16.***]: FAILED! => {"changed": false, "msg": "AnsibleUndefinedVariable: 'ansible.vars.hostvars.HostVarsVars object' has no attribute 'private_ip'"}
fatal: [54.***.***.***]: FAILED! => {"changed": false, "msg": "AnsibleUndefinedVariable: 'ansible.vars.hostvars.HostVarsVars object' has no attribute 'private_ip'"}

**Comment by dave2wave** [comment]
This problem looks similar to what you reported in #189 

Have you setup terraform.tfvars properly and did your terraform apply run properly before you ran the ansible playbook?
