### ISSUE TITLE
openmessaging-benchmark-0.0.1-SNAPSHOT is a monolith

### ISSUE THREAD

**Issue by dave2wave** [openmessaging/benchmark#208]
By compiling all the drivers into openmessaging-benchmark-0.0.1-SNAPSHOT.tar.gz we endup with a huge classpath full of drivers we don't need.

My wishlist is to find a way to select which drivers to include in the packaging.

Of course you can do this by editing the main pom.xml.

**Comment by vongosling** [comment]
@dave2wave would you like to help to polish it? I am happy to follow up on this request.

**Comment by dave2wave** [comment]
@vongosling I'm going to use the commenting out in the pom.xml approach, but someday I might learn how to make maven control which to include.

**Comment by cbornet** [comment]
maybe with Maven profiles ?
