### ISSUE TITLE
Can the average publish latency (publishLatencyAvg) be larger than end-to-end latency(endToEndLatencyAvg)?

### ISSUE THREAD

**Issue by kasun04** [openmessaging/benchmark#216]
I was using Open Messaging benchmark framework for testing the latency of Kafka. However, I observe that the calculated values of publishLatencyAvg are larger than endToEndLatencyAvg for the same test. 

I was able to reproduce this consistently for low latency tests. Is this a known issue? 

Thanks, 
Kasun

**Comment by merlimat** [comment]
the end-to-end latency is computed using timestamps taken on different nodes, so it's really not super-reliable. I think the clock are typically (in best case) skewed by ~100ms.

**Comment by kasun04** [comment]
Thanks for your response @merlimat . In my use case, both producer and consumer run on the same node. So, isn't it safe to assume that we get more reliable values for end-to-end latency?

**Comment by vongosling** [comment]
Yes.
