### ISSUE TITLE
driver-kop test failure during mvn clean install

### ISSUE THREAD

**Issue by willr3** [openmessaging/benchmark#253]
I tried to run `mvn clean install` with a fresh clone and the driver-kop build failed due to the following test:
```
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running io.openmessaging.benchmark.driver.kop.KopBenchmarkDriverTest
Configuring TestNG with: org.apache.maven.surefire.testng.conf.TestNG652Configurator@56aac163
Tests run: 3, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.399 sec <<< FAILURE!
testLoadCustomConfig(io.openmessaging.benchmark.driver.kop.KopBenchmarkDriverTest)  Time elapsed: 0.154 sec  <<< FAILURE!
java.lang.AssertionError: expected [100] but found [10]
	at org.testng.Assert.fail(Assert.java:99)
	at org.testng.Assert.failNotEquals(Assert.java:1037)
	at org.testng.Assert.assertEqualsImpl(Assert.java:140)
	at org.testng.Assert.assertEquals(Assert.java:122)
	at org.testng.Assert.assertEquals(Assert.java:907)
	at org.testng.Assert.assertEquals(Assert.java:917)
	at io.openmessaging.benchmark.driver.kop.KopBenchmarkDriverTest.testLoadCustomConfig(KopBenchmarkDriverTest.java:82)

Results :

Failed tests:   testLoadCustomConfig(io.openmessaging.benchmark.driver.kop.KopBenchmarkDriverTest): expected [100] but found [10]
```
The test passes if I add `batchingPartitionSwitchFrequencyByPublishDelay: 100` under pulsarConfig in `driver-kop/src/test/resources/kop_custom.yaml`

is that value meant to exist in the kop_custom.yaml or is the test meant to capture some other issue that is causing a test failure in my local environment?

**Comment by luk-sam** [comment]
+1

**Comment by luk-sam** [comment]
> I tried to run `mvn clean install` with a fresh clone and the driver-kop build failed due to the following test:
> 
> ```
> -------------------------------------------------------
>  T E S T S
> -------------------------------------------------------
> Running io.openmessaging.benchmark.driver.kop.KopBenchmarkDriverTest
> Configuring TestNG with: org.apache.maven.surefire.testng.conf.TestNG652Configurator@56aac163
> Tests run: 3, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.399 sec <<< FAILURE!
> testLoadCustomConfig(io.openmessaging.benchmark.driver.kop.KopBenchmarkDriverTest)  Time elapsed: 0.154 sec  <<< FAILURE!
> java.lang.AssertionError: expected [100] but found [10]
> 	at org.testng.Assert.fail(Assert.java:99)
> 	at org.testng.Assert.failNotEquals(Assert.java:1037)
> 	at org.testng.Assert.assertEqualsImpl(Assert.java:140)
> 	at org.testng.Assert.assertEquals(Assert.java:122)
> 	at org.testng.Assert.assertEquals(Assert.java:907)
> 	at org.testng.Assert.assertEquals(Assert.java:917)
> 	at io.openmessaging.benchmark.driver.kop.KopBenchmarkDriverTest.testLoadCustomConfig(KopBenchmarkDriverTest.java:82)
> 
> Results :
> 
> Failed tests:   testLoadCustomConfig(io.openmessaging.benchmark.driver.kop.KopBenchmarkDriverTest): expected [100] but found [10]
> ```
> 
> The test passes if I add `batchingPartitionSwitchFrequencyByPublishDelay: 100` under pulsarConfig in `driver-kop/src/test/resources/kop_custom.yaml`
> 
> is that value meant to exist in the kop_custom.yaml or is the test meant to capture some other issue that is causing a test failure in my local environment?


work-around:

while waiting for fix update value in source code (line 82) [esolver.DefaultLegacyArtifactCollector.recurse(DefaultLegacyArtifactCollector.java:278)
        at org.apache.maven.repository.legacy.r](https://github.com/openmessaging/benchmark/blob/73081cf96fd9d545ed8392dee3b7bc8c47ab3a52/driver-kop/src/test/java/io/openmessaging/benchmark/driver/kop/KopBenchmarkDriverTest.java#L82)
  

old:
  assertEquals(pulsarConfig.batchingPartitionSwitchFrequencyByPublishDelay, 100);
  
new:
  assertEquals(pulsarConfig.batchingPartitionSwitchFrequencyByPublishDelay, 100);
