### ISSUE TITLE
Driver-pravega does not compile anymore

### ISSUE THREAD

**Issue by franvila** [openmessaging/benchmark#262]
After this PR #259 has been merged, the compilation stopped working.

```
Failed to execute goal on project driver-pravega: Could not resolve dependencies for project io.openmessaging.benchmark:driver-pravega:jar:0.0.1-SNAPSHOT: Could not find artifact io.pravega:pravega-client:jar:0.12.0 in jfrog (https://oss.jfrog.org/jfrog-dependencies)
```

The [pravega](https://github.com/pravega/pravega/releases) 0.12.0 does not exist yet, it is still on 0.10.1 version.

**Comment by vongosling** [comment]
Pls try again.

**Comment by franvila** [comment]
It's working now after reverting this change. Thanks you @vongosling!
