### ISSUE TITLE
Create a CLI to generate the Benchmarking workload YAML configuration files.

### ISSUE THREAD

**Issue by david-streamlio** [openmessaging/benchmark#32]
Rather than have the users choose from a list of pre-defined configurations, it might be useful to have a simple command line tools that will take in all of these values as parameters, and generate the YAML configuration file automatically.

e.g. ./bin/generate-workload --num-topics=3 --msg-size=100kb --num-producers=5 ....etc.

**Comment by vongosling** [comment]
good idea
