### ISSUE TITLE
Produce-only requests should be able to use all worker nodes when using distributed workers

### ISSUE THREAD

**Issue by travisdowns** [openmessaging/benchmark#405]
Currently if you specify a "no consume" workload (e.g., with 0 subscriptions per topic) it will still allocate 1/2 (rounded up) of all worker nodes to consumer workers, even though consumers will not be started.

Instead, we should allocate all nodes to producers.

**Comment by merlimat** [comment]
Yes, it does make a lot of sense to make that improvement. The current logic, was to try to keep producer/consumers separated to make it easier to implement, although it's not really the best strategy.
