### ISSUE TITLE
Extract and define benchmark api 

### ISSUE THREAD

**Issue by Hellojungle** [openmessaging/benchmark#77]

**Comment by merlimat** [comment]
@Hellojungle Benchmark API is already defined at https://github.com/openmessaging/openmessaging-benchmark/tree/master/driver-api/src/main/java/io/openmessaging/benchmark/driver

**Comment by vongosling** [comment]
@merlimat I think @Hellojungle mean that we could separate API  and framework/concrete into two repositories.

**Comment by Hellojungle** [comment]
@merlimat Just as @vongosling  have said, and further, I think we could separate API, framework, concrete  into three repositories

**Comment by sijie** [comment]
@vongosling @Hellojungle : openmessaging-benchmark is a very small project right now. I don't see the point of separating them into 3 repositories. It will just make build and maintenance very complicated.

**Comment by Hellojungle** [comment]
@sijie I think separate into API and concrete two repositories is enough and it will be more convenient for other message systems to use the API repository to finish their driver.
